### PR TITLE
feature/gen-boxes

### PR DESCRIPTION
**Pull request by dakotagporter**
# Description
Adding a new shell script that will generate box files from a directory containing tif image files. The script will generate a box file for each image by keeping the same base file name and placing it in the same directory. This will set up the required file structure and formats to begin Tesseract training on image data.

## Changes

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge

### CODE REVIEW

**Comment by BobBriksz** [comment]
Looks good! Nice and concise shell script!

**Review by BobBriksz — COMMENTED** [review]
Nice and concise shell script! I saw it in action yesterday good work!

**Review by BobBriksz — APPROVED** [review]

**Review by leibo411 — APPROVED** [review]
Very well commented and understandable code. Looks good!

**Comment by drewamorbordelon** [comment]
When needing to create/update the OCR model this is a necessary script with clear and easy to follow comments.  Good Stuff!

**Pull request merged**
